### ISSUE TITLE
Updated release on PyPi

### ISSUE THREAD

**Issue by fdintino** [SilentCircle/iap-local-receipt#4]
Would it be possible to upload a distribution of the latest version to PyPi? Thanks!

**Comment by fdintino** [comment]
@efine looks like you converted the readme to reStructuredTex, presumably for a new pypi release, but then maybe forgot to upload it?

**Comment by efine** [comment]
@fdintino, I did indeed convert the README to reStructuredText, but I didn't forget to upload it - I tried very hard!

It turns out that 

- The PyPI index owner is/was someone at Silent Circle.
- Nobody I have spoken to has the credentials, or even remembers having had the credentials, for the associated PyPI account. (Although this codebase was last uploaded in 2014, I've been a highly motivated KeePass user since 2012, and the credentials are not in my KeePass DB, so...).
- Presumably due to email domain name changes, the reset email address (whatever it may be) does not appear to work.

I have opened a [ticket](https://sourceforge.net/p/pypi/support-requests/746/#) with PyPI support to attempt to resolve the situation. I will keep this ticket updated as the situation changes.

Many apologies.

**Comment by efine** [comment]
I submitted a [bug request](https://github.com/pypa/pypi-legacy/issues/690) to PyPI, since I have had no response from the support forum.

**Comment by fdintino** [comment]
Thanks for keeping on top of this, I really appreciate it.

**Comment by efine** [comment]
Someone from PyPI helped me out, so now v0.2.0 of this package has been uploaded to PyPI. I have taken steps to ensure this particular issue won't happen again.
